### ISSUE TITLE
"from FitPlot import plotFit" in example notebooks

### ISSUE THREAD

**Issue by vtcloud** [dokester/BayesicFitting#1]
Hi,
I'm getting an error that in some example notebooks the following routine could not be found:

from FitPlot import plotFit

I could find plotFit in source/Plotter.py, however, the keyword "ftr" was missing.
Thank you,
VT

**Comment by dokester** [comment]
Hi VT,

I just realised that there are two modules that have a plotFit method: source/Plotter.py and test/FitPlot.py.
In the examples I used the one from the test directory. I should have used the one from the source dir.
I will correct this in the next upload.

Thanks for your comments. They help me to improve the package.

Do Kester.

**Comment by dokester** [comment]
Hi VT,

I have uploaded new examples that now use the Plotter in source and a new setup.py. 
I removed FrogEngine.py and OrderEngine.py (for the time being)

Do.
