### ISSUE TITLE
IterativeFitter tries to import removed GenGaussErrorDistribution.py

### ISSUE THREAD

**Issue by rfshipman** [dokester/BayesicFitting#11]
from BayesicFitting Import Fitter fails because the module GenGaussErrorDistribution is still called from IterativeFitter.py.  
also NestedSampler.py and ScaledErrorDistribution.py mention it.

**Comment by dokester** [comment]
Hi Russ,

Thanks for he info. I am working on it. Give me an hour or so.

Do.

**Comment by dokester** [comment]
Hi Russ,

A new version (2.2.1) has been installed on GitHub and pipy. I hope that this one works better. 

Again, thanks for finding the mistakes. For some reasons it is a lot more complicated to find them myself.

Do.

**Comment by rfshipman** [comment]
Thanks Do.  That fixed it.  Cheers, Russ
