### ISSUE TITLE
Hardcoded number of cycles for Monte Carlo

### ISSUE THREAD

**Issue by ivvv** [dokester/BayesicFitting#14]
The number of cycles for Monte Carlo calculation (file `MonteCarlo.py`) of the confidence interval is currently hardcoded in the class to 25. Maybe it would be better to have this as an input parameter the user can change, if necessary.

**Comment by dokester** [comment]
The number of cycles in MonteCarlo.py is determined by the mcycles attribute, which is by default 25.
However it can be set to something else:

mc = MonteCarlo( data, model, covariance )
mc.mcycles = 100

At this moment it is not possible to set the mcycles in the initiation of the class. In the next version I will change this.

**Comment by ivvv** [comment]
Thanks, yes, I figure it out. Initially I thought it was hardcoded in the __init__.py. So, I believe this issue can be closed.
