### ISSUE TITLE
Fitter fails with error when using weights

### ISSUE THREAD

**Issue by ivvv** [dokester/BayesicFitting#15]
I am trying to fit a polynomial model of order 2 to data with weights. The `.fit()` fails with the following error:

`ValueError: Length of passed values is 3, index implies 189.
`
The size of each x, y and weights is 189. As far as I can tell, the error is in `getHessian()` method. 

A simple notebook with demonstration of the problem is available [here](https://www.dropbox.com/s/1cdw3ssx4t3grem/bayesic_fit_weights.ipynb?dl=0), the data file used in the notebook is [here](https://www.dropbox.com/s/hn96esd3l5htsmg/data_out.csv?dl=0).

Let me know if you have problems accessing the code and the datafile.

**Comment by dokester** [comment]
Hi Ivan,

When I am running the script, it runs ok. However 2 remarks:

1. Weights in my package are defined such that when weights=N this is equivalent to having N observations with weight=1. Your weights are quite high, in the thousands, meaning that you have about a million (virtual) observations. In principle that is OK and it should work (as it does by me). But I would divide all weights by 1000 which leaves the fitting results exactly the same.

2. In the traceback I see that the error occurs in a pandas-package. 
The numpy.inner method is somehow picked up by pandas/core/series.py. It should be picked up by numpy. the BayesicFitting package does not depend on pandas. So something is wrong at your site; I think with miniconda.
In any case I find the fact that this error is possible, very disturbing. I thought namespace was well defined in python.

Let me hear if something should be done on this side.

Do Kester

**Comment by ivvv** [comment]
Yes, indeed it's something to do with `pandas`.  Somehow passing an argument of class `pandas.core.series.Series` messes things up. Converting the `Series` object to numpy array with `.to_numpy()` fixes it. 

I am not sure if something needs to be done on your side. Documenting it, perhaps.

**Comment by ivvv** [comment]
Note, however, that the `fit()` works if `weights=None` even if I provide `pandas` Series objects. So, the clash is somewhere in the branching for `weights != None`. 

Note that I only have to do `.to_numpy()` for the weights, `x` and `y` could stay as Series objects.

**Comment by dokester** [comment]
Yes, I am looking into that. I see that at some moment, inside Fitter, I redefine xdata as a numpy array. Maybe I should do the same with ydata and weights. 

Could you check if this helps in your case:

y = np.array( df.y )
w = np.array( df.w )

If so I will insert these lines in the fitters. I cannot use the .to_numpy() fix as I don’t have pandas available. 

Please let me know

Do.

**Comment by ivvv** [comment]
Yes, this works with no error.

**Comment by dokester** [comment]
Thanks. I will put the array conversion in the fitters. Then these pandas series will be automatically converted to numpy arrays.

It will be in the next version of BayesicFitting.

Do.

**Comment by dokester** [comment]
The changes are in the new version 2.6.1.

**Comment by ivvv** [comment]
Hello Do,

I have a question regarding the BayesicFitting.BSplinesModel. I am
using it to model some observations with the following parameters:

model = bf.BSplinesModel( nrknots=15, order=2, min=0, max=20 )

It all works good and the residuals of (data - model) all make sense.
But I would like to extrapolate beyond the max value. When I try to
evaluate the model at points above my max value of 20 it fails. If I
use e.g. max=25, then it fails with singular matrix, which is probably
expected as I don't have data points above 20.0.

Any suggestions on how to proceed? Is my idea to use BSplines in this
way (extrapolation) not making much sense with this model?

Thanks,
Ivan

**Comment by dokester** [comment]
Hi Ivan,

BSplinesModel and BasicSplinesModel are both strictly defined on the range [knots[0]..knots[-1]]. They are constituted of base functions of 3rd order and 2 times continuously differentiable. In the picture you see these 8 base functions for 6 knots BSplinesModel. The 8 parameters are amplitudes of the base functions.

As you can see, they are NOT defined outside the range.

The model SplinesModel does not have this limitation. It can be extrapolated outside its range. However unless your extrapolation is very small, I seriously doubt it will help you. The extrapolations grow with the 3rd order of the distance.

Sorry I can’t help you further.
Do.

**Comment by ivvv** [comment]
Thanks for explaining it so clearly and so quickly. I'll figure out an
alternative approach for the predicted range beyond the final observation.

Cheers,
Ivan
