### ISSUE TITLE
Can't import BayesicFitting: No module named 'BayesicFitting.source.CrossEngine'

### ISSUE THREAD

**Issue by MigoMueller** [dokester/BayesicFitting#16]
`import BayesicFitting` results in error message

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-389169ef999f> in <module>
----> 1 import BayesicFitting

~/anaconda3/envs/miricle.test/lib/python3.8/site-packages/BayesicFitting/__init__.py in <module>
     47 from .source.ConstantModel import ConstantModel
     48 from .source.ConvergenceError import ConvergenceError
---> 49 from .source.CrossEngine import CrossEngine
     50 from .source.CurveFitter import CurveFitter
     51 #from .source.CyclicResults import CyclicResults

ModuleNotFoundError: No module named 'BayesicFitting.source.CrossEngine'`

This is under BayesicFitting 2.7.0 installed via pip

**Comment by MigoMueller** [comment]
Not surprising it should bug out: file CrossEngine.py is indeed missing on BayesicFitting/source

**Comment by dokester** [comment]
The import of CrossEngine is removed from the __init__.py list. Some time ago I decided that it was not a good, i.e. efficient and random, engine. So I removed it. But I forgot to remove it from the import list.
In version 2.7.2 this issue is resolved.
