### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by vtcloud** [dokester/BayesicFitting#2]
Hi Do,

I'm still working on getting everything installed. During installation I'm getting a few python errors:

file: OrderEngine.py, line 98: command is unfinished
file:FrogEngine.py", line 149:   indx = []S   SyntaxError: invalid syntax

finally I'm getting the following error message during installation:

Searching for python>=3.5
Reading https://pypi.python.org/simple/python/
No local packages or working download links found for python>=3.5
error: Could not find suitable distribution for Requirement.parse('python>=3.5')

However, my python version is 3.6!

lastly, it would be great if the relevant files would be copied to the "site-packages" directory of my python installation. Then you do not need to add anything to the python path.

Again, thanks,
VT

**Comment by dokester** [comment]
Hi VT,

Thanks for your comments. The two classes you mention should not (yet) be in the distribution. OrderEngine is part of my effort to bring non-classical fitting problems into the domain of NestedSampler. Problem where the order of some nodes need to be optimised. Think e.g. the traveling salesman, or making a schedule. 
FrogEngine is a relic from my JAVA version of this package; it is now superseded by the clearly superior GalileanEngine. 
Both classes slipped through the cracks. I will remove them in a next upload.
I am also working on my setup.py file such that it can be 'pip'ped into the site packages directories. However I am not an expert in this area. So I am struggling along. I will upload a new setup.py version that performs better, I hope. The issue with python>=3.5 is resolved as python is not a package and it should not be in "install_requires".

Again thanks for your comments; they help me to improve the package.

Do Kester.
