### ISSUE TITLE
Attempted import of GaussPriorNew causes failure

### ISSUE THREAD

**Issue by hbushouse** [dokester/BayesicFitting#20]
In the 3.1.0 release that was just released, the import at https://github.com/dokester/BayesicFitting/blob/master/BayesicFitting/__init__.py#L27 is causing failures, because there isn't a source module called `GaussPriorNew`, only `GaussPrior`.

**Comment by dokester** [comment]
Hi Howard,

The GaussPriorNew.py should not be in __init__.py. I am going to fix it. It takes some time however to resolve it.

For now you can comment it out. 

Thanks for the notification.

Do Kester.

**Comment by hbushouse** [comment]
> 

It's killing our builds of the JWST calibration pipeline pkg, so we've just pinned the version of `BayesicFitting` to <3.1.0 for now in our setup.cfg. Will unpin once the fix is available.

**Comment by dokester** [comment]
The offending line has been removed; and also a test which addressed GaussPriorNew.

**Comment by dokester** [comment]
Close
