### ISSUE TITLE
Numpy 2.0 - compatibility issue

### ISSUE THREAD

**Issue by matteogabba** [dokester/BayesicFitting#24]
The current version of BayesicFitting is not compatible with numpy 2.0.
Are you thinking to update the package?

**Comment by dokester** [comment]
I have a couple of questions before I can answer this issue.
1. Are scipy, astropy and mathplotlib compatible with numpy 2.0?
2. Do I need to stay compatible with numpy 1.9?
3. Does a program/script exist that I can feed this package and that will list possible issues?

**Comment by matteogabba** [comment]
1. Here you find a list of libraries compatible with numpy 2.0
https://github.com/numpy/numpy/issues/26191
2. I am not able to answer this question.
3. The ruff plugins is what you are looking for, I believe.
https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin

**Comment by dokester** [comment]
Thank you, Matteo, for your answers. 

I installed ruff and ran it on my code directories.

> ruff check BayesicFitting --select NPY201

and it resulted in "All check passed". So I assume that BayesicFitting only used the basic stuff from numpy that remained stable over the transition from 1 to 2.

How do I announce to the world that BayesicFitting is actually compatible with 2.0 while at the same time it also runs with previous versions >= 1.9.

While I am a good scientific programmer, the administration part of maintaining a package is much less of my expertise.  That is why I need some help sometimes. 

Thanks again.

**Comment by matteogabba** [comment]
Hey Do,
That is strange.
The first time,
I've installed your package, I used numpy 2.0 and I run in a compatibility issue.
After downgrading to 1.9 it was solved.

**Comment by matteogabba** [comment]
Perhaps, you can try to install it with numpy 2.0 as I did and run some examples for testing purposes.
My background is also not of a software engineer.

**Comment by dokester** [comment]
It took a while to familiarise myself with pyenv but now I can choose which python version and which numpy etc I am using.

Yesterday (7-10-2024) I released a new version (3.2.2) which is compatible with numpy >=2.

Closing down this issue.
