### ISSUE TITLE
LevenbergMarquardtFitter: singular matrix error solution

### ISSUE THREAD

**Issue by matteogabba** [dokester/BayesicFitting#26]
Hi Do,

I am having some troubles with a singular matric error when using the LevenbergMarquardtFitter (see below).
It only happens with some data.
Do you have any idea about how to solve it?

`File [~\anaconda3\envs\tpspy\Lib\site-packages\BayesicFitting\source\LevenbergMarquardtFitter.py:199](http://localhost:8889/lab/tree/notebooks/matteo/~/anaconda3/envs/tpspy/Lib/site-packages/BayesicFitting/source/LevenbergMarquardtFitter.py#line=198), in LevenbergMarquardtFitter.fit(self, data, weights, par0, keep, limits, maxiter, tolerance, verbose, plot, accuracy, callback)
    195     self.first = False
    197 while self.iter < maxiter :
--> 199     trypar, trychi = self.trialfit( trypar, fitIndex, data, fitWgts, verbose, maxiter )
    200     self.model.parameters = trypar
    202     tol = tolerance if self.chi < 1 else tolerance * self.chi

File [~\anaconda3\envs\tpspy\Lib\site-packages\BayesicFitting\source\LevenbergMarquardtFitter.py:254](http://localhost:8889/lab/tree/notebooks/matteo/~/anaconda3/envs/tpspy/Lib/site-packages/BayesicFitting/source/LevenbergMarquardtFitter.py#line=253), in LevenbergMarquardtFitter.trialfit(self, params, fi, data, weights, verbose, maxiter)
    251 for k in range( nfit ) :
    252     hessian[k,k] *= ( 1 + self.lamda )
--> 254 newpar = fitpar + 0.5 * numpy.linalg.solve( hessian, vector )
    256 onEdge, edgePar, edgeInd = self.checkLimits( newpar, fi )
    257 onEdge = False

File [~\anaconda3\envs\tpspy\Lib\site-packages\numpy\linalg\linalg.py:409](http://localhost:8889/lab/tree/notebooks/matteo/~/anaconda3/envs/tpspy/Lib/site-packages/numpy/linalg/linalg.py#line=408), in solve(a, b)
    407 signature = 'DD->D' if isComplexType(t) else 'dd->d'
    408 extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 409 r = gufunc(a, b, signature=signature, extobj=extobj)
    411 return wrap(r.astype(result_t, copy=False))

File [~\anaconda3\envs\tpspy\Lib\site-packages\numpy\linalg\linalg.py:112](http://localhost:8889/lab/tree/notebooks/matteo/~/anaconda3/envs/tpspy/Lib/site-packages/numpy/linalg/linalg.py#line=111), in _raise_linalgerror_singular(err, flag)
    111 def _raise_linalgerror_singular(err, flag):
--> 112     raise LinAlgError("Singular matrix")

LinAlgError: Singular matrix`

**Comment by dokester** [comment]
A singular matrix error most of the time points to a degenerate model, i.e. 2 parameters measure essentially the same thing.

Please have a look at https://dokester.github.io/BayesicFitting/docs/troubles.html
where I have collected errors and mistakes that I mostly made myself. And a way forward.

**Comment by matteogabba** [comment]
Hi,
Thanks for the quick reply!

I would exclude a degeneracy problem.
I am fitting a simple single-exponential model with constant background:
$f(t) =  bg + a*e^{-kt}$

Below, an example of a curve giving the error.
With very similar curves, I don't get the same error.

If I understand correctly the error arose when trying to invert a singular matrix.
Isn't it possible to use alternative methods like pseudoinverse based on SVD?
There is a function implemented numpy: linalg.pinv()
I may be wrong though.

![image](https://github.com/user-attachments/assets/0dead25e-2807-47c6-9d25-7355adb9efdc)

**Comment by dokester** [comment]
I was a little too fast. In LevenbergMarquardt It is not the solution that is sought by inverting a matrix, but only the direction to the solution. Far away from the top of an exponential function, the derivative is (almost) zero. This causes the matrix (of directions) to be singular. Remedies are better initial values for the parameters. It does not matter how you obtain them as long as they are near the top.

**Comment by matteogabba** [comment]
Hey Do,

I estimate the start guesses from the data as:

bg: last point of the decay
amplitude: $y_{max} - y_{min}$
decay time: from the half-time $t_{1/2}$

They should be quite close to the true values.

These are the data above, if you want to paly around with them.

times:
array([  0.       ,   0.1992175,   0.398435 ,   0.5976516,   0.796869 ,
         0.9960863,   1.195303 ,   1.3945204,   1.5937377,   1.792955 ,
         1.992172 ,   2.191389 ,   2.3906065,   2.589824 ,   2.789041 ,
         2.988258 ,   3.187475 ,   3.386692 ,   3.58591  ,   3.785127 ,
         3.984344 ,   4.183561 ,   4.382778 ,   4.581995 ,   4.781213 ,
         4.98043  ,   5.179647 ,   5.378864 ,   5.578081 ,   5.777298 ,
         5.976516 ,   6.175733 ,   6.374951 ,   6.574167 ,   6.773384 ,
         6.972602 ,   7.171819 ,   7.371036 ,   7.5702535,   7.76947  ,
         7.968687 ,   8.167905 ,   8.367122 ,   8.56634  ,   8.765556 ,
         8.964773 ,   9.163991 ,   9.363208 ,   9.562425 ,   9.761643 ,
         9.960859 ,  10.160076 ,  10.359294 ,  10.558512 ,  10.757729 ,
        10.956946 ,  11.156162 ,  11.355379 ,  11.554596 ,  11.753815 ,
        11.953032 ,  12.152249 ,  12.351465 ,  12.550682 ,  12.749901 ,
        12.949118 ,  13.148335 ,  13.347551 ,  13.546769 ,  13.745985 ,
        13.945204 ,  14.144421 ,  14.343638 ,  14.542854 ,  14.742071 ,
        14.94129  ,  15.140507 ,  15.339724 ,  15.538941 ,  15.738157 ,
        15.937374 ,  16.136593 ,  16.335809 ,  16.535027 ,  16.734244 ,
        16.93346  ,  17.132677 ,  17.331896 ,  17.531113 ,  17.730329 ,
        17.929546 ,  18.128763 ,  18.327982 ,  18.527199 ,  18.726416 ,
        18.925633 ,  19.124849 ,  19.324066 ,  19.523285 ,  19.722502 ,
        19.921719 ,  20.120936 ,  20.320152 ,  20.519371 ,  20.718588 ,
        20.917805 ,  21.117022 ,  21.316239 ,  21.515455 ,  21.714674 ,
        21.913891 ,  22.113108 ,  22.312325 ,  22.511541 ,  22.71076  ,
        22.909977 ,  23.109194 ,  23.308411 ,  23.507628 ,  23.706844 ,
        23.906063 ,  24.10528  ,  24.304497 ,  24.503714 ,  24.702931 ,
        24.902147 ,  25.101366 ,  25.300583 ,  25.499799 ,  25.699017 ,
        25.898234 ,  26.097452 ,  26.296669 ,  26.495886 ,  26.695105 ,
        26.894319 ,  27.093539 ,  27.292753 ,  27.491972 ,  27.691189 ,
        27.890406 ,  28.089625 ,  28.288839 ,  28.488059 ,  28.687273 ,
        28.886492 ,  29.085709 ,  29.284926 ,  29.484144 ,  29.683359 ,
        29.882579 ,  30.081797 ,  30.281012 ,  30.480229 ,  30.679445 ,
        30.878664 ,  31.077883 ,  31.277099 ,  31.476317 ,  31.675532 ,
        31.874749 ,  32.073965 ,  32.273184 ,  32.472403 ,  32.671619 ,
        32.870836 ,  33.070051 ,  33.269269 ,  33.468489 ,  33.667704 ,
        33.866923 ,  34.066139 ,  34.265356 ,  34.464575 ,  34.663789 ,
        34.863009 ,  35.062224 ,  35.261442 ,  35.460661 ,  35.659876 ,
        35.859095 ,  36.058309 ,  36.257529 ,  36.456743 ,  36.655962 ,
        36.855179 ,  37.054396 ,  37.253615 ,  37.452829 ,  37.652049 ,
        37.851267 ,  38.050482 ,  38.249699 ,  38.448916 ,  38.648134 ,
        38.847353 ,  39.046569 ,  39.245787 ,  39.445002 ,  39.644219 ,
        39.843435 ,  40.042654 ,  40.241873 ,  40.441089 ,  40.640307 ,
        40.839522 ,  41.038739 ,  41.237959 ,  41.437174 ,  41.636393 ,
        41.835609 ,  42.034826 ,  42.234045 ,  42.433259 ,  42.632479 ,
        42.831694 ,  43.030913 ,  43.230131 ,  43.429346 ,  43.628565 ,
        43.827779 ,  44.026999 ,  44.226214 ,  44.425432 ,  44.624651 ,
        44.823866 ,  45.023085 ,  45.222299 ,  45.421519 ,  45.620739 ,
        45.819952 ,  46.019169 ,  46.218386 ,  46.417605 ,  46.616823 ,
        46.816039 ,  47.015257 ,  47.214472 ,  47.413689 ,  47.612906 ,
        47.812124 ,  48.011343 ,  48.210559 ,  48.409777 ,  48.608992 ,
        48.808209 ,  49.007429 ,  49.206644 ,  49.405863 ,  49.605079 ,
        49.804297 ,  50.003515 ,  50.202729 ,  50.401949 ,  50.601164 ,
        50.800383 ,  50.999601 ,  51.198816 ,  51.398035 ,  51.597249 ,
        51.796469 ,  51.995684 ,  52.194903 ,  52.394121 ,  52.593336 ,
        52.792555 ,  52.991769 ,  53.190989 ,  53.390209 ,  53.589422 ,
        53.788641 ,  53.987856 ,  54.187075 ,  54.386294 ,  54.585509 ,
        54.784729 ,  54.983942 ,  55.183161 ,  55.382376 ,  55.581595 ,
        55.780813 ,  55.980029 ,  56.179247 ,  56.378462 ,  56.577679 ,
        56.776899 ,  56.976114 ,  57.175333 ,  57.374549 ,  57.573767 ,
        57.772986 ,  57.972199 ,  58.171419 ,  58.370634 ,  58.569853 ,
        58.769069 ,  58.968289 ,  59.167499 ,  59.366719 ,  59.565939 ,
        59.765159 ,  59.964379 ,  60.163589 ,  60.362809 ,  60.562029 ,
        60.761244 ,  60.960459 ,  61.159674 ,  61.358889 ,  61.558109 ,
        61.757329 ,  61.956539 ,  62.155759 ,  62.354979 ,  62.554199 ,
        62.753419 ,  62.952629 ,  63.151849 ,  63.351065 ,  63.550284 ,
        63.749499 ,  63.948713 ,  64.147929 ,  64.347149 ,  64.546369 ,
        64.745589 ,  64.944799 ,  65.144019 ,  65.343239 ,  65.542459 ,
        65.741675 ,  65.940889 ,  66.140104 ,  66.339323 ,  66.538539 ,
        66.737759 ,  66.936969 ,  67.136189 ,  67.335409 ,  67.534629 ,
        67.733849 ,  67.933059 ,  68.132279 ,  68.331499 ,  68.530714 ,
        68.729933 ,  68.929144 ,  69.128359 ,  69.327579 ,  69.526799 ,
        69.726009 ,  69.925229 ,  70.124449 ,  70.323669 ,  70.522889 ,
        70.722099 ,  70.921319 ,  71.120535 ,  71.319754 ,  71.518969 ,
        71.718184 ,  71.917399 ,  72.116619 ,  72.315839 ,  72.515059 ,
        72.714269 ,  72.913489 ,  73.112709 ,  73.311929 ,  73.511145 ,
        73.710359 ,  73.909575 ,  74.108793 ,  74.308009 ,  74.507229 ,
        74.706439 ,  74.905659 ,  75.104879 ,  75.304099 ,  75.503319 ,
        75.702529 ,  75.901749 ,  76.100969 ,  76.300184 ,  76.499403 ,
        76.698614 ,  76.897833 ,  77.097049 ,  77.296269 ,  77.495479 ,
        77.694699 ,  77.893919 ,  78.093139 ,  78.292359 ,  78.491569 ,
        78.690789 ,  78.890009 ,  79.089224 ,  79.288439 ,  79.487654 ,
        79.686869 ,  79.886089 ,  80.085309 ,  80.284529 ,  80.483739 ,
        80.682959 ,  80.882179 ,  81.081399 ,  81.280615 ,  81.479829 ,
        81.679045 ,  81.878264 ,  82.077479 ,  82.276699 ,  82.475909 ,
        82.675129 ,  82.874349 ,  83.073569 ,  83.272789 ,  83.471999 ,
        83.671219 ,  83.870439 ,  84.069655 ,  84.268873 ,  84.468084 ,
        84.667303 ,  84.866519 ,  85.065739 ,  85.264949 ,  85.464169 ,
        85.663389 ,  85.862609 ,  86.061829 ,  86.261039 ,  86.460259 ,
        86.659479 ,  86.858694 ,  87.057913 ,  87.257124 ,  87.456343 ,
        87.655559 ,  87.854779 ,  88.053999 ,  88.253209 ,  88.452429 ,
        88.651649 ,  88.850869 ,  89.050089 ,  89.249299 ,  89.448515 ,
        89.647734 ,  89.846949 ,  90.046169 ,  90.245379 ,  90.444599 ,
        90.643819 ,  90.843039 ,  91.042259 ,  91.241469 ,  91.440689 ,
        91.639909 ,  91.839125 ,  92.038344 ,  92.237555 ,  92.436773 ,
        92.635989 ,  92.835209 ,  93.034419 ,  93.233639 ,  93.432859 ,
        93.632079 ,  93.831299 ,  94.030509 ,  94.229729 ,  94.428949 ,
        94.628164 ,  94.827383 ,  95.026594 ,  95.225813 ,  95.425029 ,
        95.624249 ,  95.823469 ,  96.022679 ,  96.221899 ,  96.421119 ,
        96.620339 ,  96.819559 ,  97.018769 ,  97.217989 ,  97.417204 ,
        97.616419 ,  97.815639 ,  98.014849 ,  98.214069 ,  98.413289 ,
        98.612509 ,  98.811729 ,  99.010939 ,  99.210159 ,  99.409379 ,
        99.608595 ,  99.807814 , 100.007025 , 100.206244 , 100.405459 ,
       100.604679 , 100.803889 , 101.003109 , 101.202329 , 101.401549 ,
       101.600769 , 101.799979 , 101.999199 , 102.198419 , 102.397635 ,
       102.596853 , 102.796065 , 102.995283 , 103.194499 , 103.393719 ,
       103.592939 , 103.792149 , 103.991369 , 104.190589 , 104.389809 ,
       104.589029 , 104.788239 , 104.987459 , 105.186674 , 105.385893 ,
       105.585109 , 105.784323 , 105.983539 , 106.182759 , 106.381979 ,
       106.581199 , 106.780409 , 106.979629 , 107.178849 , 107.378069 ,
       107.577284 , 107.776495 , 107.975714 , 108.174929 , 108.374149 ,
       108.573359 , 108.772579 , 108.971799 , 109.171019 , 109.370239 ,
       109.569449 , 109.768669 , 109.967889 , 110.167105 , 110.366324 ,
       110.565535 , 110.764753 , 110.963969 , 111.163189 , 111.362409 ,
       111.561619 , 111.760839 , 111.960059 , 112.159279 , 112.358499 ,
       112.557709 , 112.756929 , 112.956144 , 113.155363 , 113.354579 ,
       113.553793 , 113.753009 , 113.952229 , 114.151449 , 114.350669 ,
       114.549879 , 114.749099 , 114.948319 , 115.147539 ])

values:
array([25.31, 25.3 , 25.28, 25.27, 25.25, 25.23, 25.2 , 25.18, 25.15,
       25.12, 25.09, 25.06, 25.03, 24.99, 24.96, 24.93, 24.89, 24.86,
       24.82, 24.79, 24.75, 24.72, 24.68, 24.65, 24.61, 24.58, 24.54,
       24.51, 24.47, 24.44, 24.41, 24.38, 24.34, 24.31, 24.28, 24.25,
       24.22, 24.19, 24.16, 24.13, 24.1 , 24.07, 24.04, 24.02, 23.99,
       23.96, 23.93, 23.91, 23.88, 23.86, 23.83, 23.81, 23.79, 23.76,
       23.74, 23.71, 23.69, 23.67, 23.65, 23.63, 23.61, 23.58, 23.57,
       23.55, 23.53, 23.51, 23.49, 23.47, 23.45, 23.43, 23.42, 23.4 ,
       23.38, 23.37, 23.35, 23.33, 23.32, 23.3 , 23.29, 23.27, 23.26,
       23.24, 23.23, 23.22, 23.2 , 23.19, 23.17, 23.16, 23.15, 23.14,
       23.12, 23.11, 23.1 , 23.09, 23.08, 23.06, 23.05, 23.04, 23.03,
       23.02, 23.01, 23.  , 22.99, 22.98, 22.97, 22.96, 22.95, 22.94,
       22.93, 22.92, 22.91, 22.9 , 22.9 , 22.89, 22.88, 22.87, 22.86,
       22.86, 22.85, 22.84, 22.83, 22.82, 22.82, 22.81, 22.8 , 22.8 ,
       22.79, 22.78, 22.78, 22.77, 22.76, 22.76, 22.75, 22.74, 22.74,
       22.73, 22.73, 22.72, 22.71, 22.71, 22.7 , 22.7 , 22.69, 22.69,
       22.68, 22.68, 22.67, 22.67, 22.66, 22.66, 22.65, 22.65, 22.64,
       22.64, 22.63, 22.63, 22.62, 22.62, 22.62, 22.61, 22.61, 22.6 ,
       22.6 , 22.6 , 22.59, 22.59, 22.59, 22.58, 22.58, 22.57, 22.57,
       22.57, 22.56, 22.56, 22.56, 22.55, 22.55, 22.55, 22.54, 22.54,
       22.54, 22.53, 22.53, 22.53, 22.52, 22.52, 22.52, 22.51, 22.51,
       22.51, 22.51, 22.5 , 22.5 , 22.5 , 22.5 , 22.5 , 22.49, 22.49,
       22.49, 22.49, 22.48, 22.48, 22.48, 22.48, 22.47, 22.47, 22.47,
       22.47, 22.46, 22.46, 22.46, 22.46, 22.46, 22.46, 22.45, 22.45,
       22.45, 22.45, 22.45, 22.44, 22.44, 22.44, 22.44, 22.44, 22.44,
       22.43, 22.43, 22.43, 22.43, 22.43, 22.43, 22.42, 22.42, 22.42,
       22.42, 22.42, 22.42, 22.42, 22.41, 22.41, 22.41, 22.41, 22.41,
       22.41, 22.41, 22.41, 22.4 , 22.4 , 22.4 , 22.4 , 22.4 , 22.4 ,
       22.4 , 22.4 , 22.39, 22.39, 22.39, 22.39, 22.39, 22.39, 22.39,
       22.39, 22.38, 22.38, 22.38, 22.38, 22.38, 22.38, 22.38, 22.38,
       22.38, 22.38, 22.38, 22.38, 22.38, 22.38, 22.37, 22.37, 22.37,
       22.37, 22.37, 22.37, 22.37, 22.37, 22.37, 22.37, 22.37, 22.36,
       22.37, 22.36, 22.36, 22.36, 22.36, 22.36, 22.36, 22.36, 22.36,
       22.36, 22.36, 22.36, 22.36, 22.36, 22.36, 22.35, 22.35, 22.35,
       22.35, 22.35, 22.35, 22.35, 22.35, 22.35, 22.35, 22.35, 22.35,
       22.35, 22.35, 22.35, 22.35, 22.35, 22.34, 22.34, 22.35, 22.34,
       22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.34,
       22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.34,
       22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.34, 22.33, 22.33,
       22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33,
       22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33,
       22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33,
       22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33,
       22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33, 22.33,
       22.33, 22.32, 22.33, 22.32, 22.32, 22.32, 22.32, 22.32, 22.33,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32, 22.32,
       22.32, 22.32, 22.32, 22.32, 22.32, 22.31, 22.32, 22.32, 22.32,
       22.32, 22.31, 22.32, 22.32, 22.31, 22.31, 22.32, 22.32, 22.31,
       22.32, 22.31, 22.31, 22.32, 22.32, 22.31, 22.32, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31, 22.31,
       22.31, 22.31, 22.31])

**Comment by dokester** [comment]
If you want a decaying ExpModel, yoy either have to start the second parameter as a negative value, or set the keyword decay=True in the invocation.

model = ExpModel( decay=True ) + PolynomialModel( 0 )

The documentaion of the model says:

    Exponential Model.

        f( x:p ) = p_0 * exp( p_1 * x )

    where p_0 = amplitude
          p_1 = slope
    As always x = input.

    The parameters are initialized at {1.0, -1.0}. It is a non-linear model.

    Beware of a positive 2nd parameter; when positive the model is going off
    to Infinity very quickly.

    When decay is True the model changes into a decay model:

        f( x:p ) = p_0 * exp( - p_1 * x )

    The parameters are initialized at {1.0, 1.0}.

**Comment by matteogabba** [comment]
Hey,
I do that already.
It should not be a problem with the model.
I am fitting hundreds of curves more or less similar.
With most of them the fit works. 
Only a few raise the error and I don't have a reasonable explanation.
The data I've shared above are an example giving the error.

**Comment by dokester** [comment]
I cannot reproduce you error. When I write 

```
model = ExpModel() + PolynomialModel( 0 )
model.parameters = [5, -10, 20]
ftr = LevenbergMarquardtFitter( x, model )
par = ftr.fit( y, plot=True )
print( par )
```

It just converges to a par = [ 3.2001222  -0.07514478 22.31510291].

If I take a positive par[1] (=10), the convergence fails on "Too many iterations", not the same as your error, I see now.

Then I tried to do it with your initial values:

```
model = ExpModel( ) + PolynomialModel( 0 )
print( model )
p2 = y[-1]
p0 = y[0] - p2
k1 = numpy.where( y - p2 < (p0/2) )
p1 = -1 / x[k1][0]

model.parameters = [p0, p1, p2]
print( "initial  ", model.parameters )
ftr = LevenbergMarquardtFitter( x, model )
par = ftr.fit( y, plot=True )
print( "result   ", par )
```
It outputs:
```
Exp: f( x:p ) = p_0 * exp( p_1 * x ) +
Polynomial: f( x:p ) = p_2
initial   [ 3.         -0.09653167 22.31      ]
result    [ 3.19993087 -0.07515527 22.31527225]
```
So I am still not sure what is happening.

**Comment by matteogabba** [comment]
Hey Do,
I checked my code.
There was a typo in the function estimating the starting guesses.
I corrected it and solved the problem.
Thanks a lot for your help!

**Comment by dokester** [comment]
I gather this issue can be closed, considering the last remarks.
