### ISSUE TITLE
SyntaxWarning: invalid escape sequence with python 3.12

### ISSUE THREAD

**Issue by braingram** [dokester/BayesicFitting#27]
There are several docstrings that contain invalid escape sequences:
https://github.com/dokester/BayesicFitting/blob/acab59918d709f0e473d16dc29d86ebf5f2e479a/BayesicFitting/source/EtalonModel.py#L40
The use of `\pi` in the above string leads to a `SyntaxWarning` in python 3.12.

A minimal example of this can be seen by trying to make a string with `\pi` with python 3.12.

```python
Python 3.12.4 (main, Nov 26 2024, 13:35:36) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s = "\pi"
<stdin>:1: SyntaxWarning: invalid escape sequence '\p'
```

The issue is not limited to the above example.

**Comment by dokester** [comment]
In version 3.2.3 the invalid escape sequences have been removed. Or the docstring has been changed into a raw-string. 
I hope this is allowed. I could not find a "yes, it is allowed" nor a "no it is not".

Closing this issue.
